"""
setup_creds.py  —  One-time setup: derive Polymarket API credentials from your private key
and write them to a .env file.

Usage:
    python setup_creds.py

You will be prompted for:
  - Your private key (from reveal.magic.link/polymarket or MetaMask)
  - Your Polymarket proxy/funder address (shown on the deposit page)
"""

import os
import sys
import getpass
from py_clob_client.client import ClobClient

HOST     = "https://clob.polymarket.com"
CHAIN_ID = 137


def main():
    print("=" * 60)
    print("  Polymarket BTC Bot — Credential Setup")
    print("=" * 60)
    print()
    print("This script derives your CLOB API credentials from your")
    print("private key and saves them to a .env file.\n")

    # Get private key
    pk = getpass.getpass("Private key (0x...): ").strip()
    if not pk.startswith("0x"):
        pk = "0x" + pk

    # Get funder address
    funder = input("Funder/proxy address (leave blank for MetaMask EOA): ").strip()

    # Wallet type
    sig_type = 1 if funder else 0
    label = "Email/Magic proxy" if funder else "MetaMask/EOA"
    print(f"\nWallet type detected: {label}")

    print("\nConnecting to Polymarket…")
    try:
        if funder:
            client = ClobClient(
                HOST, key=pk, chain_id=CHAIN_ID,
                signature_type=1, funder=funder,
            )
        else:
            client = ClobClient(HOST, key=pk, chain_id=CHAIN_ID)

        creds = client.create_or_derive_api_creds()
        print("✅ Credentials derived successfully!\n")

    except Exception as e:
        print(f"❌ Failed to create credentials: {e}")
        sys.exit(1)

    # Starting bankroll
    bankroll = input("Starting bankroll in USDC (default 10.0): ").strip() or "10.0"
    min_bet  = input("Minimum bet size in USDC (default 5.0): ").strip()  or "5.0"

    # Write .env
    env_content = f"""# Polymarket BTC Bot — credentials
# Generated by setup_creds.py — DO NOT commit this file to git!

POLY_PRIVATE_KEY={pk}
POLY_FUNDER_ADDRESS={funder}
POLY_SIGNATURE_TYPE={sig_type}
POLY_API_KEY={creds.api_key}
POLY_API_SECRET={creds.api_secret}
POLY_API_PASSPHRASE={creds.api_passphrase}

STARTING_BANKROLL={bankroll}
MIN_BET={min_bet}

# ── Telegram Notifications (optional) ────────────────────────────────────────
# Enable with: python bot.py --telegram
# Get a bot token from @BotFather on Telegram
# Get your chat ID from @userinfobot or @getidsbot
# TELEGRAM_BOT_TOKEN=123456789:AABBCCDDEEFFaabbccddeeff
# TELEGRAM_CHAT_ID=-1001234567890
"""

    with open(".env", "w") as f:
        f.write(env_content)

    print("✅ .env file written.\n")
    print("You can now run the bot:")
    print("  python bot.py --dry-run --mode safe --window 5")
    print("  python bot.py --mode safe --window 5")
    print("  python bot.py --mode degen --window 15 --dry-run")


if __name__ == "__main__":
    main()
